name: Notify on Invalid Tag Creation

on:
  push:
    tags:
      - "*"

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Extract Tag and Commit Information
      - name: Get Tag Name and Commit SHA
        id: tag_info
        run: |
          # Extract the tag name from GITHUB_REF
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag name: $TAG_NAME"

          # Get the commit SHA associated with the tag
          TAG_COMMIT_SHA=$(git rev-parse "$TAG_NAME")
          echo "Tag commit SHA: $TAG_COMMIT_SHA"

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "TAG_COMMIT_SHA=$TAG_COMMIT_SHA" >> $GITHUB_ENV

      # Step 3: Determine Base Branch
      - name: Get Branch from Commit SHA
        id: branch_info
        run: |
          # Get the branch containing the commit
          BASE_BRANCH=$(git branch -r --contains $TAG_COMMIT_SHA | grep -v '->' | sed 's/origin\///' | head -n 1)
          echo "Base branch: $BASE_BRANCH"

          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

          if [ -z "$BASE_BRANCH" ]; then
            echo "Failed to determine the base branch."
            exit 1
          fi

      # Step 4: Notify if Tag is Not Created from Master
      - name: Notify if Not on Master
        if: env.BASE_BRANCH != 'master'
        run: |
          MESSAGE="Alert: Tag '${{ env.TAG_NAME }}' created from branch '${{ env.BASE_BRANCH }}', not 'master'."

          echo "$MESSAGE"

          # Send Slack Notification
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"'"$MESSAGE"'"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

          # Optional Email Notification
          echo "Subject: GitHub Alert - Invalid Tag Creation\n\n${MESSAGE}" | sendmail -v ${{ secrets.NOTIFY_EMAIL }}
