name: Notify on Tag from Non-Master Branch

on:
  create:
    tags:    # Trigger only for tag creation events.

jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Branch
        run: |
          TAG_COMMIT_SHA=$(git rev-parse ${{ github.event.ref }})
          BASE_BRANCH=$(git branch --contains $TAG_COMMIT_SHA | grep -v '\*' | grep -v 'main')
          
          if [[ -z "$BASE_BRANCH" ]]; then
            echo "Tag is from master. No alert needed."
            exit 0
          else
            echo "Tag from $BASE_BRANCH."
            echo "$BASE_BRANCH" > branch.txt
          fi
        shell: bash

      - name: Send Slack Notification
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          BRANCH=$(cat branch.txt)
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "⚠️ Alert: Tag created on branch `$BRANCH` instead of master!"
          }' $SLACK_WEBHOOK_URL

      - name: Send Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com   # SMTP server address
          server_port: 587                   # SMTP port
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'GitHub Alert: Tag Creation from Non-Master Branch'
          to: 'admin@example.com'
          from: 'noreply@example.com'
          body: |
            A new tag has been created on a branch other than master.
            Branch Name: $(cat branch.txt)
