name: Tag Alert Mechanism

on:
  push:
    tags:
      - "*"

jobs:
  check-tag-origin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Tag and Branch Info
        id: tag-info
        run: |
          # Get the tag name from GitHub context
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

          # Find the commit that the tag points to
          TAG_COMMIT_SHA=$(git rev-list -n 1 $TAG_NAME)
          echo "TAG_COMMIT_SHA=$TAG_COMMIT_SHA" >> $GITHUB_ENV

          # Determine the branch from which the tag was created
          BASE_BRANCH=$(git branch -r --contains $TAG_COMMIT_SHA | grep -v '\->' | sed 's/origin\///g' | head -n 1)
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

      - name: Display Tag and Branch Info
        run: |
          echo "Tag Name: $TAG_NAME"
          echo "Tag Commit SHA: $TAG_COMMIT_SHA"
          echo "Base Branch: $BASE_BRANCH"


      - name: Fail if base branch is not master
        if: env.BASE_BRANCH != 'master'
        run: echo "Tag created from branch: $BASE_BRANCH. Notifying stakeholders."

      - name: Notify on Slack
        if: env.BASE_BRANCH != 'master'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: your-slack-channel-id
          text: >
            ⚠️ Tag `${{ env.TAG_NAME }}` created from branch `${{ env.BASE_BRANCH }}`, not master.

      - name: Send Email Notification
        if: env.BASE_BRANCH != 'master'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "GitHub Alert: Tag Created from Non-Master Branch"
          body: "⚠️ A tag was created from branch '${{ env.BASE_BRANCH }}', which is not the 'master' branch."
  
