name: Notify on Tag from Non-Master Branch

on:
  create:
    tags: # Trigger only for tag creation events.

jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code with full history
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full commit history

      # Step 2: Determine the branch for the tag
      - name: Check Branch
        run: |
          # Extract the tag name from GitHub context
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag Name: $TAG_NAME"

          # Get the commit SHA for the tag
          TAG_COMMIT_SHA=$(git rev-parse $TAG_NAME)
          echo "Tag Commit SHA: $TAG_COMMIT_SHA"

          # Determine which branch contains this commit (excluding master)
          BASE_BRANCH=$(git branch --contains $TAG_COMMIT_SHA | grep -v '\*' | grep -v 'master' | xargs)
          echo "Base Branch: $BASE_BRANCH"

          # If no branch is found, assume it's master or detached
          if [[ -z "$BASE_BRANCH" ]]; then
            echo "Tag is from master or detached commit. No alert needed."
            exit 0
          else
            echo "Tag from $BASE_BRANCH."
            echo "$BASE_BRANCH" > branch.txt
          fi
        shell: bash

      # Step 3: Send Slack Notification if the tag is from a non-master branch
      - name: Send Slack Notification
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          BRANCH=$(cat branch.txt)
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "⚠️ Alert: Tag created on branch `'$BRANCH'` instead of master!"
          }' $SLACK_WEBHOOK_URL

      # Step 4: Send Email Notification
      - name: Send Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com   # SMTP server address
          server_port: 587                   # SMTP port
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'GitHub Alert: Tag Creation from Non-Master Branch'
          to: 'admin@example.com'
          from: 'noreply@example.com'
          body: |
            A new tag has been created on a branch other than master.
            Branch Name: $(cat branch.txt)
