name: Notify on Invalid Tag Creation

on:
  push:
    tags:
      - "*"

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Extract Tag Name and Validate
      - name: Get Tag Name and Validate Base Branch
        id: validate_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

          # Retrieve commit SHA for the tag
          TAG_COMMIT_SHA=$(git rev-list -n 1 "$TAG_NAME")
          echo "TAG_COMMIT_SHA=${TAG_COMMIT_SHA}" >> $GITHUB_ENV

          # Determine the branch the tag commit belongs to
          BASE_BRANCH=$(git branch -r --contains "${TAG_COMMIT_SHA}" | grep -v '->' | sed 's/origin\///' | head -n 1)
          echo "BASE_BRANCH=${BASE_BRANCH}" >> $GITHUB_ENV

          if [ -z "$BASE_BRANCH" ]; then
            echo "Unable to determine the base branch. Exiting."
            exit 1
          fi

          echo "Tag Name: $TAG_NAME"
          echo "Commit SHA: $TAG_COMMIT_SHA"
          echo "Base Branch: $BASE_BRANCH"

      # Step 3: Conditional Step for Notification if Not on Master
      - name: Notify if Invalid Branch
        if: env.BASE_BRANCH != 'master'
        run: |
          MESSAGE="Alert: Tag '${{ env.TAG_NAME }}' created from branch '${{ env.BASE_BRANCH }}', which is not 'master'."

          echo "$MESSAGE"

          # Send Slack Notification
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"'"$MESSAGE"'"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

          # Optional Email Notification
          echo "Subject: GitHub Alert - Invalid Tag Creation\n\n${MESSAGE}" | sendmail -v ${{ secrets.NOTIFY_EMAIL }}
