name: Tag Alert

on:
  push:
    tags:
      - "*"

jobs:
  tag-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract the Tag Name
        id: extract-tag
        run: |
          # Extract the tag name from the GitHub context
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag Name: $TAG_NAME"
    
